# Generated by Django 5.0.4 on 2024-05-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptionKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k4", models.CharField(max_length=200)),
                ("op", models.CharField(max_length=200)),
            ],
        ),
    ]
