# Generated by Django 5.0.4 on 2024-05-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0004_alter_encryptionkeys_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="adm1",
        ),
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="adm6",
        ),
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="iccid",
        ),
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="imsi",
        ),
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="pin1",
        ),
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="pin2",
        ),
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="puk1",
        ),
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="puk2",
        ),
        migrations.RemoveField(
            model_name="encryptionkeys",
            name="size",
        ),
    ]
