# Generated by Django 5.0.4 on 2024-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "datagenApp",
            "0008_encryptionkeys_adm1_rand_encryptionkeys_adm6_rand_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptionkeys",
            name="adm1",
            field=models.CharField(default="1234FFFF", max_length=8),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="adm6",
            field=models.CharField(default="1234FFFF", max_length=8),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="iccid",
            field=models.CharField(default="FFFFFFFFFFFFFFFFFFFFFF", max_length=20),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="imsi",
            field=models.CharField(default="1111111111111111", max_length=15),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="k4",
            field=models.CharField(default="FFFFFFFFFFFFFFFFFFFFF", max_length=64),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="op",
            field=models.CharField(default="FFFFFFFFFFFFFFFFFFFFF", max_length=64),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="pin1",
            field=models.CharField(default="1234FFFF", max_length=8),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="pin2",
            field=models.CharField(default="1234FFFF", max_length=8),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="puk1",
            field=models.CharField(default="1234FFFF", max_length=8),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="puk2",
            field=models.CharField(default="1234FFFF", max_length=8),
        ),
        migrations.AlterField(
            model_name="encryptionkeys",
            name="size",
            field=models.CharField(default="FFFFFFFFFFFFFFFFFFFFF", max_length=5),
        ),
    ]
