# Generated by Django 5.0.4 on 2024-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0011_encryptionkeys_pin1_rand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptionkeys",
            name="pin1_rand",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
