# Generated by Django 5.0.4 on 2024-05-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0016_securitykeysrandomization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricalDataJson",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("parameter", models.CharField(default="DEFAULT", max_length=10)),
                ("lclip", models.IntegerField(default=0)),
                ("rclip", models.IntegerField(default=32)),
            ],
        ),
    ]
