# Generated by Django 5.0.4 on 2024-05-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0017_electricaldatajson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricaldatajson",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
