# Generated by Django 5.0.4 on 2024-05-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0018_alter_electricaldatajson_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphicalDataJson",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("parameter", models.CharField(default="DEFAULT", max_length=10)),
                ("lclip", models.IntegerField(default=0)),
                ("rclip", models.IntegerField(default=32)),
            ],
        ),
        migrations.AlterField(
            model_name="electricaldatajson",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
