# Generated by Django 5.0.4 on 2024-05-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0019_graphicaldatajson_alter_electricaldatajson_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zong_Input_Dataframe",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("iccid", models.CharField(default="NaN", max_length=20)),
                ("imsi", models.CharField(default="NaN", max_length=15)),
            ],
        ),
    ]
