# Generated by Django 5.0.4 on 2024-05-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0024_alter_zong_input_dataframe_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricalOutputData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=64)),
                ("column_value", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="DynamicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=50)),
                ("column_value", models.CharField(max_length=200)),
                (
                    "id1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_data",
                        to="datagenApp.zong_input_dataframe",
                    ),
                ),
            ],
        ),
    ]
