# Generated by Django 5.0.4 on 2024-05-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0025_electricaloutputdata_dynamicdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFrameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
