# Generated by Django 5.0.4 on 2024-05-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0026_dataframemodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataFrameModel",
        ),
        migrations.RemoveField(
            model_name="electricaloutputdata",
            name="column_name",
        ),
        migrations.RemoveField(
            model_name="electricaloutputdata",
            name="column_value",
        ),
        migrations.AddField(
            model_name="electricaloutputdata",
            name="row_value",
            field=models.CharField(default="NaN", max_length=512),
        ),
        migrations.DeleteModel(
            name="DynamicData",
        ),
    ]
