# Generated by Django 5.0.4 on 2024-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0027_delete_dataframemodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphicalOutputData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_value", models.CharField(default="NaN", max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ServerOutputData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_value", models.CharField(default="NaN", max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name="electricaloutputdata",
            name="row_value",
            field=models.CharField(default="NaN", max_length=1024),
        ),
    ]
