# Generated by Django 5.0.4 on 2024-05-03 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0028_graphicaloutputdata_serveroutputdata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textfile",
            name="id",
        ),
        migrations.AddField(
            model_name="textfile",
            name="file_id",
            field=models.AutoField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
