# Generated by Django 5.0.4 on 2024-05-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0029_remove_textfile_id_textfile_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="startingparams",
            name="file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="datagenApp.textfile",
            ),
        ),
    ]
