# Generated by Django 5.0.4 on 2024-05-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0030_startingparams_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptionkeys",
            name="file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="datagenApp.textfile",
            ),
        ),
        migrations.AddField(
            model_name="securitykeys",
            name="file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="datagenApp.textfile",
            ),
        ),
        migrations.AddField(
            model_name="securitykeysrandomization",
            name="file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="datagenApp.textfile",
            ),
        ),
        migrations.AlterField(
            model_name="textfile",
            name="file_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
