# Generated by Django 5.0.4 on 2024-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0031_encryptionkeys_file_securitykeys_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textfile",
            name="file_id",
            field=models.AutoField(
                auto_created=True, default=0, primary_key=True, serialize=False
            ),
        ),
    ]
