# Generated by Django 5.0.4 on 2024-05-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0032_alter_textfile_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textfile",
            name="file_id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
