# Generated by Django 5.0.4 on 2024-05-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0034_alter_startingparams_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitykeys",
            name="file",
            field=models.ForeignKey(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datagenApp.textfile",
            ),
        ),
    ]
