# Generated by Django 5.0.4 on 2024-05-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datagenApp", "0036_alter_encryptionkeys_file_alter_securitykeys_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securitykeys",
            name="file",
        ),
        migrations.RemoveField(
            model_name="securitykeysrandomization",
            name="file",
        ),
    ]
